### ISSUE TITLE
Ambiguous docs now that there are >1 endpoints supported

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-storage#18]
![image](https://user-images.githubusercontent.com/247555/75802721-cc989d80-5d42-11ea-8eed-df46d924f68c.png)

It's impossible to tell which is the v1beta1 API and which is the v1 API. Doc title needs to include the version.

**Comment by busunkim96** [comment]
This should be fixed upstream in the generator templates. Filed an issue https://github.com/googleapis/gapic-generator/issues/3108

**Comment by meredithslota** [comment]
Root cause fixed in https://github.com/googleapis/gapic-generator-python/pull/435 but will check to see if that fix has made its way through to here. :)

**Comment by meredithslota** [comment]
Not fixed: https://googleapis.dev/python/bigquerystorage/1.1.0/index.html but "latest" only includes v1: https://googleapis.dev/python/bigquerystorage/latest/index.html

**Comment by busunkim96** [comment]
I think this is because v1 is the only endpoint https://github.com/googleapis/python-bigquery-storage/tree/master/google/cloud

**Comment by tswast** [comment]
Closing as we dropped the v1beta1 client in the 2.0 release.
